CREATE TABLE USERS (
	USERID SERIAL PRIMARY KEY,
	EMAIL VARCHAR(255) unique,
	USERNAME VARCHAR(255) unique,
	PASSWORD VARCHAR(255)
);

CREATE TABLE GROUPS (
	GROUPID SERIAL PRIMARY KEY,
	CREATED_BY INT REFERENCES USERS (USERID),
	CREATED_AT TIMESTAMP
);

CREATE TABLE USERMESSAGES (
	SENDERID INT REFERENCES USERS (USERID),
	RECEIVERID INT REFERENCES USERS (USERID),
	CONTENT TEXT
);

CREATE TABLE GROUPMESSAGES (
	SENDERID INT REFERENCES USERS (USERID),
	GROUPID INT REFERENCES GROUPS (GROUPID),
	SENT_AT TIMESTAMP,
	CONTENT TEXT
);

CREATE TABLE GROUPMEMBERS (
	GROUPID INT REFERENCES GROUPS (GROUPID),
	USERID INT REFERENCES USERS (USERID)
);